# Etapa de construcción (build)
FROM node:20-alpine AS builder

WORKDIR /app

# Copiar solo el package.json y package-lock.json para instalar dependencias
COPY ecommerce-backend/package*.json ./

# Limpiar la caché de npm para evitar problemas de bloqueo
RUN npm cache clean --force

# Instalar solo las dependencias de producción
RUN npm ci --production

# Copiar el resto del código de la aplicación
COPY ecommerce-backend/ .

# Construir el proyecto (NestJS)
RUN npm run build

# Etapa de producción
FROM node:20-alpine

WORKDIR /app

# Copiar solo los archivos generados desde la etapa de construcción
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules

# Exponer el puerto
EXPOSE 4000

# Comando de inicio
CMD ["node", "dist/main.js"]
